Repository projectceladon/device-intel-common, pull requests merged in 2024-08, with the labels that each got.

#217 Updated kernel headers for v6.1.92 rebase
  kernel/lts2022-chromium/kernel-headers/linux/iwl-vendor-cmd.h
  kernel/lts2022-chromium/kernel-headers/linux/nl80211.h
Labels: PR approved, Valid commit message, Pending Developer Approval, Engineering Build Successful

#219 Fix vendor.img creation failing with latest build_image script
  firmware.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#212 Thermal Daemon configuration for MTL NUC Platform
  thermal/thermal-daemon/thermal-conf.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#221 Fix BT HFP call can not reject call issue
  device-type/overlay-car/frameworks/base/core/res/res/values/config.xml
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#223 Make max connected audio a2dp device as one
  bluetooth/overlay-car/packages/modules/Bluetooth/android/app/res/values/config.xml
Labels: PR approved, Valid commit message, Engineering Build Successful
