Repository projectceladon/device-intel-common, pull requests merged in 2024-09, with the labels that each got.

#228 Migrate gpt_ini2bin.py to python3
  gpt_bin/gpt_ini2bin.py
Labels: PR approved, Valid commit message, Developer Approved, Integration Approved, Engineering Build Successful

#226 Migrate gpt_ini2bin.py to python3
  gpt_bin/gpt_ini2bin.py
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#232 Creating overlay for Config Nl80211RegChangedEvent
  rro_overlays/WifiOverlay/Android.bp
  rro_overlays/WifiOverlay/AndroidManifest.xml
  rro_overlays/WifiOverlay/OWNERS
  rro_overlays/WifiOverlay/res/values/config.xml
Labels: PR approved, Valid commit message, Pending Developer Approval, Engineering Build Successful

#231 Removal of unused 6.1 and 5.15 kernels
  kernel/linux-intel-lts2021/kernel-headers/linux/iwl-vendor-cmd.h
  kernel/linux-intel-lts2021/kernel-headers/linux/nl80211.h
  kernel/linux-intel-lts2022/kernel-headers/linux/iwl-vendor-cmd.h
  kernel/linux-intel-lts2022/kernel-headers/linux/nl80211.h
  kernel/lts2021-chromium/kernel-headers/linux/iwl-vendor-cmd.h
  kernel/lts2021-chromium/kernel-headers/linux/nl80211.h
  kernel/lts2022-chromium/kernel-headers/linux/iwl-vendor-cmd.h
  kernel/lts2022-chromium/kernel-headers/linux/nl80211.h
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#227 Migrate gpt_ini2bin.py to python3
  gpt_bin/gpt_ini2bin.py
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#225 dkms: optimize the dg2 kernel driver loading time
  firmware.mk
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#233 Removal of unused 5.15 kernel header
  kernel/linux-intel-lts2021/kernel-headers/linux/iwl-vendor-cmd.h
  kernel/linux-intel-lts2021/kernel-headers/linux/nl80211.h
  kernel/lts2021-chromium/kernel-headers/linux/iwl-vendor-cmd.h
  kernel/lts2021-chromium/kernel-headers/linux/nl80211.h
Labels: PR approved, Valid commit message, Developer Approved, Engineering Build Successful

#235 Create LICENSE
  LICENSE
Labels: Invalid commit message, Pending Developer Approval, Engineering Build Not Started, Pending PR Review
